### ISSUE TITLE
User can't use ActionChains with EyesWebDriver

### ISSUE THREAD

**Issue by mkvetko** [applitools/eyes.selenium.python#3]
**Module versions:**
selenium 3.3.3
eyes-selenium 3.7.1 

When I initialize selenium ActionChains object with EyesWebDriver instance it fails with following error:
```
Eyes driver instance check
Traceback (most recent call last):
  File "w3c_attribute_missing.py", line 15, in <module>
    eyes_action = ActionChains(eyes_driver)
  File "C:\Python34\lib\site-packages\selenium\webdriver\common\action_chains.py", line 69, in __init__
    if self._driver.w3c:
AttributeError: 'EyesWebDriver' object has no attribute 'w3c'
```

Seems like new version of selenium is checking whether web driver is w3c compliant or not. 
Please fix it. 

Full example to reproduce the issue:
```
from applitools.eyes import EyesWebDriver, Eyes
from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains

selenium_driver = webdriver.Chrome()
eyes_driver = EyesWebDriver(selenium_driver, Eyes())

#This passes
selenium_action = ActionChains(selenium_driver)

#This fails due to missing w3c attribute on driver instance
eyes_action = ActionChains(eyes_driver)
```

**Comment by danielputerman** [comment]
Closed in PR by @mkvetko. Thanks!
