### ISSUE TITLE
check_region of entire element fails in versions apper 3.12.0

### ISSUE THREAD

**Issue by Infernion** [applitools/eyes.selenium.python#32]
Version 3.12.0 is able to take screenshot of the entire element while higher versions can't.

https://trello.com/c/zBqG4fkj/330-python-check-region

**Comment by nunessf** [comment]
Might this be the reason why I can't use Check Region By Element on native apps?

**Comment by Infernion** [comment]
Hi @nunessf, actually this functionality wasn't tested yet. Which error did you get?

**Comment by nunessf** [comment]
It throws this exception: 
`WebDriverException: Message: Method is not implemented`

On appium logs: 
```
[debug] [W3C (ec773ebb)] Calling AppiumDriver.execute() with args: ["return arguments[0].style.overflow;",[{"element-6066-11e4-a52e-4f735466cecf":"fb1e555d-56b9-4540-85d5-f3bfd2461c32","ELEMENT":"fb1e555d-56b9-4540-85d5-f3bfd2461c32"}],"ec773ebb-8612-4343-bf50-6412c6b44dc8"]
[debug] [W3C (ec773ebb)] Encountered internal error running command: NotImplementedError: Method is not implemented
[debug] [W3C (ec773ebb)]     at AndroidUiautomator2Driver.extensions.execute (C:\Users\USER-Admin\AppData\Roaming\npm\node_modules\appium\node_modules\appium-android-driver\lib\commands\execute.js:12:9)
[debug] [W3C (ec773ebb)]     at curCommandCancellable._bluebird.default.resolve.then (C:\Users\USER-Admin\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\driver.js:291:18)
[debug] [W3C (ec773ebb)]     at tryCatcher (C:\Users\USER-Admin\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\node_modules\bluebird\js\main\util.js:26:23)
[debug] [W3C (ec773ebb)]     at Promise._settlePromiseFromHandler (C:\Users\USER-Admin\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\node_modules\bluebird\js\main\promise.js:510:31)
[debug] [W3C (ec773ebb)]     at Promise._settlePromiseAt (C:\Users\USER-Admin\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\node_modules\bluebird\js\main\promise.js:584:18)
[debug] [W3C (ec773ebb)]     at Promise._settlePromiseAtPostResolution (C:\Users\USER-Admin\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\node_modules\bluebird\js\main\promise.js:248:10)
[debug] [W3C (ec773ebb)]     at Async._drainQueue (C:\Users\USER-Admin\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\node_modules\bluebird\js\main\async.js:128:12)
[debug] [W3C (ec773ebb)]     at Async._drainQueues (C:\Users\USER-Admin\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\node_modules\bluebird\js\main\async.js:133:10)
[debug] [W3C (ec773ebb)]     at Immediate.Async.drainQueues (C:\Users\USER-Admin\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\node_modules\bluebird\js\main\async.js:15:14)
[debug] [W3C (ec773ebb)]     at runCallback (timers.js:705:18)
[debug] [W3C (ec773ebb)]     at tryOnImmediate (timers.js:676:5)
[debug] [W3C (ec773ebb)]     at processImmediate (timers.js:658:5)
```

**Comment by Infernion** [comment]
Ok, thanks. I see there many things should be changed to support this feature. Currently, I'm busy with other tasks, could make this fix in a week...

**Comment by nunessf** [comment]
Alright, thank you!

**Comment by ludovicmcosta** [comment]
Hello, Any news about the problem reported by @nunessf ?

**Comment by ludovicmcosta** [comment]
Hello, Any news about the problem reported by @nunessf ?

**Comment by Infernion** [comment]
hi @ludovicmcosta! Have you tried 4.x version of sdk?

**Comment by ludovicmcosta** [comment]
Yes, I have the following: eyes-selenium  4.0.8

Should the problem be fixed in this version?

**Comment by Infernion** [comment]
Oh, sorry, just checked that this is related to native apps. This behave for native apps isn't supported yet.

**Comment by ludovicmcosta** [comment]
Thanks for the quick answer :)

The problem reported by @nunessf  was also obtained when we execute the example in https://applitools.com/tutorials/appium-native-python.html#run-your-first-test. 

When method eyes.open() is executed the error below is displayed (appium logs). Is this issue related to native apps as well?

[debug] [W3C (14623234)] Calling AppiumDriver.execute() with args: ["\n    var height = undefined;\n    var width = undefined;\n    if (window.innerHeight) {\n        height = window.innerHeight;\n    } else if (document.documentElement && document.documentElement.clientHeight) {\n        height = document.documentElement.clientHeight;\n    } else {\n            var b = document.getElementsByTagName('body')[0];\n            if (b.clientHeight) {height = b.clientHeight;}\n        }\n    if (window.innerWidth) {\n        width = window.innerWidth;\n    } else if (document.documentElement && document.documentElement.clientWidth) {\n        width = document.documentElement.clientWidth;\n    } else {\n        var b = document.getElementsByTagName('body')[0];\n    if (b.clientWidth) {\n        width = b.clientWidth;}\n    }\n    return [width, height];",[],"14623234-013b-4d3f-b34b-d05282a0d447"]
[debug] [W3C (14623234)] Encountered internal error running command: NotImplementedError: Method is not implemented
[debug] [W3C (14623234)]     at AndroidUiautomator2Driver.execute (C:\Users\ludovic.costa\AppData\Roaming\npm\node_modules\appium\node_modules\appium-android-driver\lib\commands\execute.js:14:11)
[debug] [W3C (14623234)]     at curCommandCancellable._bluebird.default.resolve.then (C:\Users\ludovic.costa\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\driver.js:305:66)
[debug] [W3C (14623234)]     at tryCatcher (C:\Users\ludovic.costa\AppData\Roaming\npm\node_modules\appium\node_modules\bluebird\js\release\util.js:16:23)
[debug] [W3C (14623234)]     at Promise._settlePromiseFromHandler (C:\Users\ludovic.costa\AppData\Roaming\npm\node_modules\appium\node_modules\bluebird\js\release\promise.js:517:31)
[debug] [W3C (14623234)]     at Promise._settlePromise (C:\Users\ludovic.costa\AppData\Roaming\npm\node_modules\appium\node_modules\bluebird\js\release\promise.js:574:18)
[debug] [W3C (14623234)]     at Promise._settlePromiseCtx (C:\Users\ludovic.costa\AppData\Roaming\npm\node_modules\appium\node_modules\bluebird\js\release\promise.js:611:10)
[debug] [W3C (14623234)]     at _drainQueueStep (C:\Users\ludovic.costa\AppData\Roaming\npm\node_modules\appium\node_modules\bluebird\js\release\async.js:142:12)
[debug] [W3C (14623234)]     at _drainQueue (C:\Users\ludovic.costa\AppData\Roaming\npm\node_modules\appium\node_modules\bluebird\js\release\async.js:131:9)
[debug] [W3C (14623234)]     at Async._drainQueues (C:\Users\ludovic.costa\AppData\Roaming\npm\node_modules\appium\node_modules\bluebird\js\release\async.js:147:5)
[debug] [W3C (14623234)]     at Immediate.Async.drainQueues (C:\Users\ludovic.costa\AppData\Roaming\npm\node_modules\appium\node_modules\bluebird\js\release\async.js:17:14)
[debug] [W3C (14623234)]     at runCallback (timers.js:705:18)
[debug] [W3C (14623234)]     at tryOnImmediate (timers.js:676:5)
[debug] [W3C (14623234)]     at processImmediate (timers.js:658:5)
[HTTP] <-- POST /wd/hub/session/14623234-013b-4d3f-b34b-d05282a0d447/execute/sync 405 116 ms - 1886

**Comment by Infernion** [comment]
Do you use appium python driver or original selenium for mobile testing?  Seems it's selenium. Try to use appium-python-client for mobile testing. Also, good option would be to update library to 4.x versionSent from my Samsung Galaxy smartphone.
-------- Original message --------From: luds <notifications@github.com> Date: 12/09/2019  00:03  (GMT+02:00) To: "applitools/eyes.selenium.python" <eyes.selenium.python@noreply.github.com> Cc: Serhii Khalymon <sergiykhalimon@gmail.com>, State change <state_change@noreply.github.com> Subject: Re: [applitools/eyes.selenium.python] check_region of entire element fails in versions apper 3.12.0 (#32) Thanks for the quick answer :)
The problem reported by @nunessf  was also obtained when we execute the example in https://applitools.com/tutorials/appium-native-python.html#run-your-first-test.
When method eyes.open() is executed the error below is displayed (appium logs). Is this issue related to native apps as well?
[debug] [W3C (14623234)] Calling AppiumDriver.execute() with args: ["\n    var height = undefined;\n    var width = undefined;\n    if (window.innerHeight) {\n        height = window.innerHeight;\n    } else if (document.documentElement && document.documentElement.clientHeight) {\n        height = document.documentElement.clientHeight;\n    } else {\n            var b = document.getElementsByTagName('body')[0];\n            if (b.clientHeight) {height = b.clientHeight;}\n        }\n    if (window.innerWidth) {\n        width = window.innerWidth;\n    } else if (document.documentElement && document.documentElement.clientWidth) {\n        width = document.documentElement.clientWidth;\n    } else {\n        var b = document.getElementsByTagName('body')[0];\n    if (b.clientWidth) {\n        width = b.clientWidth;}\n    }\n    return [width, height];",[],"14623234-013b-4d3f-b34b-d05282a0d447"]
[debug] [W3C (14623234)] Encountered internal error running command: NotImplementedError: Method is not implemented
[debug] [W3C (14623234)]     at AndroidUiautomator2Driver.execute (C:\Users\ludovic.costa\AppData\Roaming\npm\node_modules\appium\node_modules\appium-android-driver\lib\commands\execute.js:14:11)
[debug] [W3C (14623234)]     at curCommandCancellable._bluebird.default.resolve.then (C:\Users\ludovic.costa\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\driver.js:305:66)
[debug] [W3C (14623234)]     at tryCatcher (C:\Users\ludovic.costa\AppData\Roaming\npm\node_modules\appium\node_modules\bluebird\js\release\util.js:16:23)
[debug] [W3C (14623234)]     at Promise._settlePromiseFromHandler (C:\Users\ludovic.costa\AppData\Roaming\npm\node_modules\appium\node_modules\bluebird\js\release\promise.js:517:31)
[debug] [W3C (14623234)]     at Promise._settlePromise (C:\Users\ludovic.costa\AppData\Roaming\npm\node_modules\appium\node_modules\bluebird\js\release\promise.js:574:18)
[debug] [W3C (14623234)]     at Promise._settlePromiseCtx (C:\Users\ludovic.costa\AppData\Roaming\npm\node_modules\appium\node_modules\bluebird\js\release\promise.js:611:10)
[debug] [W3C (14623234)]     at _drainQueueStep (C:\Users\ludovic.costa\AppData\Roaming\npm\node_modules\appium\node_modules\bluebird\js\release\async.js:142:12)
[debug] [W3C (14623234)]     at _drainQueue (C:\Users\ludovic.costa\AppData\Roaming\npm\node_modules\appium\node_modules\bluebird\js\release\async.js:131:9)
[debug] [W3C (14623234)]     at Async._drainQueues (C:\Users\ludovic.costa\AppData\Roaming\npm\node_modules\appium\node_modules\bluebird\js\release\async.js:147:5)
[debug] [W3C (14623234)]     at Immediate.Async.drainQueues (C:\Users\ludovic.costa\AppData\Roaming\npm\node_modules\appium\node_modules\bluebird\js\release\async.js:17:14)
[debug] [W3C (14623234)]     at runCallback (timers.js:705:18)
[debug] [W3C (14623234)]     at tryOnImmediate (timers.js:676:5)
[debug] [W3C (14623234)]     at processImmediate (timers.js:658:5)
[HTTP] <-- POST /wd/hub/session/14623234-013b-4d3f-b34b-d05282a0d447/execute/sync 405 116 ms - 1886

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/applitools/eyes.selenium.python/issues/32?email_source=notifications\u0026email_token=AAI4BZPV3V46UPTAOYKWBYDQJFMKFA5CNFSM4GIDBQIKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD6P4M7I#issuecomment-530564733",
"url": "https://github.com/applitools/eyes.selenium.python/issues/32?email_source=notifications\u0026email_token=AAI4BZPV3V46UPTAOYKWBYDQJFMKFA5CNFSM4GIDBQIKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD6P4M7I#issuecomment-530564733",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ludovicmcosta** [comment]
I am using appium driver and sdk version = 4.0.8.
The issue was observed with selenium and appium driver and with sdk version 4.0.8.

**Comment by Infernion** [comment]
@ludovicmcosta I've copied code from tutroial with small modification for version 4.x and I it run as expected. Code:

```
import os

from selenium import webdriver
from applitools.selenium import Eyes


class HelloWorld:

    # Initialize the eyes SDK and set your private API key.
    eyes = Eyes()

    # Desired capabilities.
    desired_caps = dict(
        platformName="Android",
        deviceName="Android Emulator",
        platformVersion="8.0",
        app="http://saucelabs.com/example_files/ContactManager.apk",
    )

    # Open the app.
    sauce_url = "https://{username}:{password}@ondemand.saucelabs.com:443/wd/hub".format(
        username=os.getenv("SAUCE_USERNAME", None),
        password=os.getenv("SAUCE_ACCESS_KEY", None),
    )
    wd = webdriver.Remote(sauce_url, desired_caps)
    wd.implicitly_wait(60)

    try:

        # Start the test.
        eyes.open(
            driver=wd,
            app_name="Contacts",
            test_name="My first Appium native Python test!",
        )

        # Visual UI testing.
        eyes.check_window("Contact list!")

        # End the test.
        eyes.close()

    finally:

        # Close the app.
        wd.quit()

        # If the test was aborted before eyes.close was called, ends the test as aborted.
        eyes.abort()
```

Could you provide exactly code that you run?
